---
- name: Secure MariaDB installation
  block:
    - name: Set root password first time
      mysql_user:
        name: root
        password: '{{ mariadb_root_password }}'
        host_all: true
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock
        login_user: root
        login_password: '{{ mariadb_root_password }}'
        column_case_sensitive: false
        plugin: mysql_native_password
      no_log: true
      ignore_errors: true

    - name: Remove anonymous users
      mysql_user:
        name: ''
        host_all: true
        state: absent
        login_user: root
        login_password: '{{ mariadb_root_password }}'
      no_log: true

    - name: Remove test database
      mysql_db:
        name: test
        state: absent
        login_user: root
        login_password: '{{ mariadb_root_password }}'
      no_log: true

    - name: Disallow root remote login
      mysql_user:
        name: root
        host: '%'
        state: absent
        login_user: root
        login_password: '{{ mariadb_root_password }}'
      no_log: true
  become: true
