---
- name: Secure MariaDB installation
  block:
    - name: Check if root user already has a password
      mysql_query:
        login_user: root
        login_password: '{{ mariadb_root_password }}'
        login_unix_socket: /var/run/mysqld/mysqld.sock
        query: "SELECT authentication_string FROM mysql.user WHERE user = 'root' AND host = 'localhost';"
      register: root_auth_check
      ignore_errors: true
      no_log: true

    - name: Set root password first time
      mysql_user:
        name: root
        password: '{{ mariadb_root_password }}'
        host_all: true
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock
        column_case_sensitive: false
      no_log: true
      when: root_auth_check.stdout is defined and root_auth_check.stdout | trim == ""
      register: root_password_changed

    - name: Disable unix_socket authentication
      lineinfile:
        path: /etc/mysql/mariadb.conf.d/50-server.cnf
        regexp: '^#?plugin-load-builtin = auth_socket\.so'
        state: absent
      notify: restart mariadb
      when: root_password_changed.changed

    - name: Remove anonymous users
      mysql_user:
        name: ''
        host_all: true
        state: absent
        login_user: root
        login_password: '{{ mariadb_root_password }}'
      no_log: true

    - name: Remove test database
      mysql_db:
        name: test
        state: absent
        login_user: root
        login_password: '{{ mariadb_root_password }}'
      no_log: true

    - name: Disallow root remote login
      mysql_user:
        name: root
        host: '%'
        state: absent
        login_user: root
        login_password: '{{ mariadb_root_password }}'
      no_log: true
