- name: Install laravel stack
  hosts: webserver
  vars_files:
    - vars/webserver.yml
  roles:
    - essential_packages
    - zsh_setup
    - nvm_node
    - nginx
    - mariadb
    - php
    - docker
    - laravel_setup
