---
- name: restart mariadb
  service:
    name: mariadb
    state: restarted

- name: reload mariadb
  service:
    name: mariadb
    state: reloaded

- name: flush privileges
  mysql_query:
    login_user: root
    login_password: '{{ mariadb_root_password }}'
    query: FLUSH PRIVILEGES
  no_log: true
