---
- name: Check if NVM is already installed
  stat:
    path: '/home/{{ host_user }}/.nvm'
  register: nvm_dir
  become: true
  become_user: '{{ host_user }}'

- name: Install NVM for user
  shell: |
    curl -o- {{ nvm_install_url }} | bash
  args:
    creates: '/home/{{ host_user }}/.nvm/nvm.sh'
    executable: /bin/bash
  become: true
  become_user: '{{ host_user }}'
  when: not nvm_dir.stat.exists

- name: Install specified Node.js version
  shell: |
    . /home/{{ host_user }}/.nvm/nvm.sh && nvm install {{ node_version }}
  args:
    creates: '/home/{{ host_user }}/.nvm/versions/node/v{{ node_version }}'
    executable: /bin/bash
  become: true
  become_user: '{{ host_user }}'

- name: Set default Node.js version
  shell: |
    . /home/{{ host_user }}/.nvm/nvm.sh && nvm alias default {{ node_version }}
  args:
    executable: /bin/bash
  become: true
  become_user: '{{ host_user }}'
  when: nvm_dir.stat.exists # Only run if NVM is installed

- name: Ensure NVM is sourced in user's shell profile
  lineinfile:
    path: '/home/{{ host_user }}/.zshrc'
    line: '[ -s "$HOME/.nvm/nvm.sh" ] && . "$HOME/.nvm/nvm.sh"  # Load NVM'
    state: present
    create: yes
  become: true
  become_user: '{{ host_user }}'
