#SPDX-License-Identifier: MIT-0
galaxy_info:
  author: virghiu
  description: Installs a specified version of PHP and its common modules on Debian/Ubuntu systems
  company: compuCenter
  license: MIT

  min_ansible_version: '2.18.2'

  platforms:
    - name: Ubuntu
      versions:
        - all

  galaxy_tags:
    - php
    - webserver
    - development
    - ubuntu
    - debian

dependencies: []
