---
- name: Install zsh
  apt:
    name: zsh
    state: present

- name: Check if Oh My Zsh is already installed
  stat:
    path: '{{ ansible_env.HOME }}/.oh-my-zsh'
  register: oh_my_zsh_installed

- name: Install Oh My Zsh
  shell: |
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: '{{ansible_env.HOME}}/.oh-my-zsh'
    executable: /bin/bash
  register: oh_my_zsh_install_result
  when: not oh_my_zsh_installed.stat.exists

- name: Install Zsh plugins
  git:
    repo: 'https://github.com/{{ item.name }}.git'
    dest: '{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/{{ item.name.split("/")[-1] }}'
    depth: 1
  loop: '{{zsh_plugins}}'
  register: zsh_plugins_installed

- name: Copy custom .zshrc configuration
  template:
    src: zshrc.j2
    dest: '{{zsh_config_file}}'
    mode: '0644'
    backup: yes
  register: zsh_config

- name: Set Zsh as the default shell
  user:
    name: '{{ ansible_env.USER }}'
    shell: /bin/zsh
  when: zsh_config.changed or not oh_my_zsh_installed.stat.exists or zsh_plugins_installed.changed

- name: Verify Zsh installation
  shell: zsh --version
  register: zsh_version_output
  changed_when: false

- name: Display Zsh version
  debug:
    msg: 'Zsh version: {{ zsh_version_output.stdout }}'

- name: Debug ansible_env.USER
  debug:
    var: ansible_env.USER
